import React from 'react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faCamera, faHeart, faWandSparkles } from '@fortawesome/free-solid-svg-icons'
import PageTransition from './PageTransition'
import family from '../assets/family.png'

const highlights = [[faCamera, 'Studio quality', 'Carefully lit portraits'], [faHeart, 'People first', 'A calm, friendly session'], [faWandSparkles, 'Made to last', 'Refined final images']]

const Aboutus = () => <PageTransition><section className="w-full max-w-6xl px-5 py-10 sm:px-8 lg:py-16"><div className="grid items-center gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><p className="mb-4 text-sm font-semibold tracking-[0.24em] text-amber-400">AAKANKSHA STUDIOS</p><h1 className="max-w-2xl text-4xl font-semibold leading-tight text-amber-50 sm:text-5xl">Framing the moments that become your favourite memories.</h1><p className="mt-6 max-w-xl text-base leading-8 text-zinc-300 sm:text-lg">Established in 2009, Aakanksha Studios has helped families, professionals, and growing little ones feel their best in front of the camera. Our indoor studio combines a relaxed experience with thoughtful lighting and polished finishing.</p><p className="mt-4 max-w-xl text-base leading-8 text-zinc-300 sm:text-lg">Whether you need a quick passport photo or a portrait to keep forever, we take the time to create images that feel natural, confident, and unmistakably you.</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{highlights.map(([icon, title, description]) => <div key={title} className="rounded-2xl border border-amber-500/25 bg-neutral-900/70 p-4"><FontAwesomeIcon icon={icon} className="mb-3 text-amber-400" /><h2 className="font-medium text-amber-50">{title}</h2><p className="mt-1 text-sm leading-5 text-zinc-400">{description}</p></div>)}</div></div><div className="relative mx-auto w-full max-w-md overflow-hidden rounded-[2rem] border border-amber-500/35 bg-gradient-to-br from-amber-950/50 to-neutral-900 p-7 shadow-2xl shadow-black/30"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,_rgba(251,191,36,.18),_transparent_45%)]" /><div className="relative"><span className="inline-flex rounded-full border border-amber-400/40 bg-black/30 px-4 py-2 text-sm font-medium text-amber-200">Since 2009</span><img src={family} alt="Family photography illustration" className="mx-auto my-6 h-56 w-full object-contain sm:h-64" /><blockquote className="border-t border-amber-500/20 pt-5 text-lg leading-8 text-amber-50">“Every photograph is a small piece of a story worth keeping.”</blockquote><p className="mt-2 text-sm text-amber-200/70">— The Aakanksha Studios team</p></div></div></div></section></PageTransition>

export default Aboutus
